import 'package:flutter/material.dart';
import '../models/environment_info.dart';

/// 所有工具的元数据注册表
/// （分离关注点：这里只定义"显示信息"，扫描逻辑在 ScannerService）
class EnvironmentRegistry {
  static final List<EnvironmentInfo> all = [
    // ── 编程语言 ──────────────────────────────────
    EnvironmentInfo(
      id: 'python',
      name: 'Python',
      description: '通用编程语言，数据科学、AI、脚本首选',
      hint: '人工智能、数据分析常用语言',
      category: EnvironmentCategory.language,
      icon: Icons.code,
      categoryColor: const Color(0xFF3B82F6),
    ),
    EnvironmentInfo(
      id: 'java',
      name: 'Java',
      description: '跨平台企业级编程语言 (JDK/JRE)',
      hint: '企业应用、Android 开发常用平台',
      category: EnvironmentCategory.language,
      icon: Icons.coffee,
      categoryColor: const Color(0xFF3B82F6),
    ),
    EnvironmentInfo(
      id: 'nodejs',
      name: 'Node.js',
      description: '基于 Chrome V8 的 JavaScript 运行时',
      hint: '用于运行 JavaScript 服务端程序',
      category: EnvironmentCategory.language,
      icon: Icons.javascript,
      categoryColor: const Color(0xFF3B82F6),
    ),
    EnvironmentInfo(
      id: 'go',
      name: 'Go (Golang)',
      description: 'Google 出品的高性能编译型语言',
      hint: '云原生、微服务开发常用',
      category: EnvironmentCategory.language,
      icon: Icons.code,
      categoryColor: const Color(0xFF3B82F6),
    ),
    EnvironmentInfo(
      id: 'rust',
      name: 'Rust',
      description: '注重安全与性能的系统级语言',
      hint: '高性能系统开发语言',
      category: EnvironmentCategory.language,
      icon: Icons.settings_ethernet,
      categoryColor: const Color(0xFF3B82F6),
    ),
    EnvironmentInfo(
      id: 'ruby',
      name: 'Ruby',
      description: '优雅的脚本语言，Rails 框架基础',
      hint: 'Web 开发脚本语言',
      category: EnvironmentCategory.language,
      icon: Icons.code,
      categoryColor: const Color(0xFF3B82F6),
    ),
    EnvironmentInfo(
      id: 'php',
      name: 'PHP',
      description: '用于 Web 后端开发的脚本语言',
      hint: '网站后台开发常用语言',
      category: EnvironmentCategory.language,
      icon: Icons.language,
      categoryColor: const Color(0xFF3B82F6),
    ),
    EnvironmentInfo(
      id: 'dotnet',
      name: '.NET / C#',
      description: 'Microsoft 跨平台开发框架 (dotnet CLI)',
      hint: 'Windows 应用与企业服务开发平台',
      category: EnvironmentCategory.language,
      icon: Icons.window,
      categoryColor: const Color(0xFF3B82F6),
    ),
    EnvironmentInfo(
      id: 'dart',
      name: 'Dart',
      description: '由 Google 设计，Flutter 开发语言',
      hint: 'Flutter 跨平台应用开发语言',
      category: EnvironmentCategory.language,
      icon: Icons.code,
      categoryColor: const Color(0xFF3B82F6),
    ),
    EnvironmentInfo(
      id: 'kotlin',
      name: 'Kotlin',
      description: 'JVM 平台现代语言，官方 Android 语言',
      hint: 'Android 开发推荐语言',
      category: EnvironmentCategory.language,
      icon: Icons.code,
      categoryColor: const Color(0xFF3B82F6),
    ),
    EnvironmentInfo(
      id: 'scala',
      name: 'Scala',
      description: 'JVM 上的函数式 + 面向对象语言',
      hint: '大数据处理常用语言',
      category: EnvironmentCategory.language,
      icon: Icons.code,
      categoryColor: const Color(0xFF3B82F6),
    ),
    EnvironmentInfo(
      id: 'perl',
      name: 'Perl',
      description: '文本处理与系统管理脚本语言',
      hint: '文本处理与系统脚本语言',
      category: EnvironmentCategory.language,
      icon: Icons.code,
      categoryColor: const Color(0xFF3B82F6),
    ),
    EnvironmentInfo(
      id: 'lua',
      name: 'Lua',
      description: '轻量级嵌入式脚本语言，游戏开发常用',
      hint: '游戏脚本语言',
      category: EnvironmentCategory.language,
      icon: Icons.code,
      categoryColor: const Color(0xFF3B82F6),
    ),
    EnvironmentInfo(
      id: 'r_lang',
      name: 'R 语言',
      description: '统计计算与数据可视化专用语言',
      hint: '统计分析与数据科学专用语言',
      category: EnvironmentCategory.language,
      icon: Icons.bar_chart,
      categoryColor: const Color(0xFF3B82F6),
    ),
    EnvironmentInfo(
      id: 'swift',
      name: 'Swift',
      description: 'Apple 出品，iOS/macOS 开发语言',
      hint: 'Apple 平台开发语言',
      category: EnvironmentCategory.language,
      icon: Icons.code,
      categoryColor: const Color(0xFF3B82F6),
    ),

    // ── 包管理器 ───────────────────────────────────
    EnvironmentInfo(
      id: 'pip',
      name: 'pip',
      description: 'Python 官方包管理工具',
      hint: '用于安装 Python 第三方库',
      category: EnvironmentCategory.packageManager,
      icon: Icons.inventory_2_outlined,
      categoryColor: const Color(0xFF8B5CF6),
    ),
    EnvironmentInfo(
      id: 'conda',
      name: 'Conda',
      description: 'Anaconda/Miniconda 环境与包管理器',
      hint: '数据科学常用，可管理多个 Python 环境',
      category: EnvironmentCategory.packageManager,
      icon: Icons.science,
      categoryColor: const Color(0xFF8B5CF6),
    ),
    EnvironmentInfo(
      id: 'npm',
      name: 'npm',
      description: 'Node.js 官方包管理器',
      hint: '用于安装 JavaScript 前端组件',
      category: EnvironmentCategory.packageManager,
      icon: Icons.inventory_2_outlined,
      categoryColor: const Color(0xFF8B5CF6),
    ),
    EnvironmentInfo(
      id: 'yarn',
      name: 'Yarn',
      description: '更快的 JavaScript 替代包管理器',
      hint: 'JavaScript 包管理工具（npm 的替代品）',
      category: EnvironmentCategory.packageManager,
      icon: Icons.inventory_2_outlined,
      categoryColor: const Color(0xFF8B5CF6),
    ),
    EnvironmentInfo(
      id: 'pnpm',
      name: 'pnpm',
      description: '节省磁盘空间的 JavaScript 包管理器',
      hint: '高效节省空间的 JavaScript 包管理工具',
      category: EnvironmentCategory.packageManager,
      icon: Icons.inventory_2_outlined,
      categoryColor: const Color(0xFF8B5CF6),
    ),
    EnvironmentInfo(
      id: 'bun',
      name: 'Bun',
      description: '超快的 JavaScript 运行时与包管理器',
      hint: '新一代极速 JavaScript 工具集',
      category: EnvironmentCategory.packageManager,
      icon: Icons.bolt,
      categoryColor: const Color(0xFF8B5CF6),
    ),
    EnvironmentInfo(
      id: 'cargo',
      name: 'Cargo',
      description: 'Rust 官方包管理与构建工具',
      hint: 'Rust 语言的包管理工具',
      category: EnvironmentCategory.packageManager,
      icon: Icons.inventory_2_outlined,
      categoryColor: const Color(0xFF8B5CF6),
    ),
    EnvironmentInfo(
      id: 'maven',
      name: 'Apache Maven',
      description: 'Java 项目构建与依赖管理工具',
      hint: 'Java 项目依赖管理和构建工具',
      category: EnvironmentCategory.packageManager,
      icon: Icons.inventory_2_outlined,
      categoryColor: const Color(0xFF8B5CF6),
    ),
    EnvironmentInfo(
      id: 'gradle',
      name: 'Gradle',
      description: 'Groovy/Kotlin DSL 构建自动化工具',
      hint: 'Android 和 Java 项目的构建工具',
      category: EnvironmentCategory.packageManager,
      icon: Icons.inventory_2_outlined,
      categoryColor: const Color(0xFF8B5CF6),
    ),
    EnvironmentInfo(
      id: 'composer',
      name: 'Composer',
      description: 'PHP 依赖管理工具',
      hint: 'PHP 项目的包管理工具',
      category: EnvironmentCategory.packageManager,
      icon: Icons.inventory_2_outlined,
      categoryColor: const Color(0xFF8B5CF6),
    ),
    EnvironmentInfo(
      id: 'gem',
      name: 'RubyGems',
      description: 'Ruby 包管理工具',
      hint: 'Ruby 语言的包管理工具',
      category: EnvironmentCategory.packageManager,
      icon: Icons.inventory_2_outlined,
      categoryColor: const Color(0xFF8B5CF6),
    ),
    EnvironmentInfo(
      id: 'poetry',
      name: 'Poetry',
      description: 'Python 现代依赖与虚拟环境管理工具',
      hint: 'Python 项目依赖管理新工具',
      category: EnvironmentCategory.packageManager,
      icon: Icons.inventory_2_outlined,
      categoryColor: const Color(0xFF8B5CF6),
    ),
    EnvironmentInfo(
      id: 'pipenv',
      name: 'Pipenv',
      description: 'Python 虚拟环境 + 依赖一体化管理',
      hint: 'Python 环境与依赖一体化管理',
      category: EnvironmentCategory.packageManager,
      icon: Icons.inventory_2_outlined,
      categoryColor: const Color(0xFF8B5CF6),
    ),
    EnvironmentInfo(
      id: 'uv',
      name: 'uv',
      description: '极速 Python 包管理器（pip 替代品）',
      hint: '新一代超快 Python 包管理器',
      category: EnvironmentCategory.packageManager,
      icon: Icons.bolt,
      categoryColor: const Color(0xFF8B5CF6),
    ),

    // ── 版本管理 ────────────────────────────────
    EnvironmentInfo(
      id: 'pyenv',
      name: 'pyenv',
      description: '同时管理多个 Python 版本的工具',
      hint: '可让一台电脑安装多个 Python 版本并随时切换',
      category: EnvironmentCategory.versionManager,
      icon: Icons.layers_outlined,
      categoryColor: const Color(0xFFF59E0B),
    ),
    EnvironmentInfo(
      id: 'nvm',
      name: 'nvm (Node 版本管理)',
      description: '管理多个 Node.js 版本',
      hint: '可随时切换不同版本的 Node.js',
      category: EnvironmentCategory.versionManager,
      icon: Icons.layers_outlined,
      categoryColor: const Color(0xFFF59E0B),
    ),
    EnvironmentInfo(
      id: 'sdkman',
      name: 'SDKMAN!',
      description: '管理 Java、Kotlin 等 JVM 工具版本',
      hint: '一键管理 JVM 生态中各种工具版本',
      category: EnvironmentCategory.versionManager,
      icon: Icons.layers_outlined,
      categoryColor: const Color(0xFFF59E0B),
    ),

    // ── 版本控制 ────────────────────────────────
    EnvironmentInfo(
      id: 'git',
      name: 'Git',
      description: '全球最流行的分布式版本控制系统',
      hint: '用于代码版本管理和多人协作开发',
      category: EnvironmentCategory.versionControl,
      icon: Icons.fork_right,
      categoryColor: const Color(0xFFEF4444),
    ),
    EnvironmentInfo(
      id: 'svn',
      name: 'SVN (Subversion)',
      description: '集中式版本控制系统',
      hint: '集中式代码版本管理工具',
      category: EnvironmentCategory.versionControl,
      icon: Icons.history,
      categoryColor: const Color(0xFFEF4444),
    ),
    EnvironmentInfo(
      id: 'gh',
      name: 'GitHub CLI',
      description: 'GitHub 官方命令行工具 (gh)',
      hint: '可在终端中操作 GitHub',
      category: EnvironmentCategory.versionControl,
      icon: Icons.hub,
      categoryColor: const Color(0xFFEF4444),
    ),

    // ── 容器 & 虚拟化 ───────────────────────────
    EnvironmentInfo(
      id: 'docker',
      name: 'Docker',
      description: '行业标准容器化平台',
      hint: '把应用打包成容器，便于部署和运行',
      category: EnvironmentCategory.container,
      icon: Icons.widgets_outlined,
      categoryColor: const Color(0xFF06B6D4),
    ),
    EnvironmentInfo(
      id: 'kubectl',
      name: 'kubectl',
      description: 'Kubernetes 命令行管理工具',
      hint: '用于管理容器集群（K8s）',
      category: EnvironmentCategory.container,
      icon: Icons.device_hub,
      categoryColor: const Color(0xFF06B6D4),
    ),
    EnvironmentInfo(
      id: 'podman',
      name: 'Podman',
      description: '无需 root 的 Docker 替代品',
      hint: 'Docker 的无守护进程替代方案',
      category: EnvironmentCategory.container,
      icon: Icons.widgets_outlined,
      categoryColor: const Color(0xFF06B6D4),
    ),
    EnvironmentInfo(
      id: 'helm',
      name: 'Helm',
      description: 'Kubernetes 应用包管理器',
      hint: 'K8s 应用的包管理和部署工具',
      category: EnvironmentCategory.container,
      icon: Icons.widgets_outlined,
      categoryColor: const Color(0xFF06B6D4),
    ),
    EnvironmentInfo(
      id: 'vagrant',
      name: 'Vagrant',
      description: '虚拟机环境构建与管理工具',
      hint: '用于快速创建和管理虚拟机',
      category: EnvironmentCategory.container,
      icon: Icons.computer,
      categoryColor: const Color(0xFF06B6D4),
    ),
    EnvironmentInfo(
      id: 'minikube',
      name: 'Minikube',
      description: '本地运行 Kubernetes 的工具',
      hint: '在本机运行迷你 K8s 集群',
      category: EnvironmentCategory.container,
      icon: Icons.device_hub,
      categoryColor: const Color(0xFF06B6D4),
    ),

    // ── 编辑器 & IDE ────────────────────────────
    EnvironmentInfo(
      id: 'vscode',
      name: 'VS Code',
      description: 'Microsoft 出品的免费代码编辑器',
      hint: '最流行的代码编辑器之一',
      category: EnvironmentCategory.ide,
      icon: Icons.developer_mode,
      categoryColor: const Color(0xFF10B981),
    ),
    EnvironmentInfo(
      id: 'vscode_insiders',
      name: 'VS Code Insiders',
      description: 'VS Code 预览版（抢先体验新功能）',
      hint: 'VS Code 的内测预览版本',
      category: EnvironmentCategory.ide,
      icon: Icons.science_outlined,
      categoryColor: const Color(0xFF10B981),
    ),

    // ── 数据库 ──────────────────────────────────
    EnvironmentInfo(
      id: 'mysql',
      name: 'MySQL',
      description: '全球最流行的开源关系型数据库',
      hint: '网站和应用后台常用数据库',
      category: EnvironmentCategory.database,
      icon: Icons.storage,
      categoryColor: const Color(0xFFF97316),
    ),
    EnvironmentInfo(
      id: 'psql',
      name: 'PostgreSQL',
      description: '功能强大的开源关系型数据库',
      hint: '高性能开源数据库',
      category: EnvironmentCategory.database,
      icon: Icons.storage,
      categoryColor: const Color(0xFFF97316),
    ),
    EnvironmentInfo(
      id: 'mongod',
      name: 'MongoDB',
      description: '文档型 NoSQL 数据库',
      hint: '适合存储非结构化数据的数据库',
      category: EnvironmentCategory.database,
      icon: Icons.storage,
      categoryColor: const Color(0xFFF97316),
    ),
    EnvironmentInfo(
      id: 'redis',
      name: 'Redis',
      description: '内存键值数据库，高性能缓存常用',
      hint: '超高速内存缓存数据库',
      category: EnvironmentCategory.database,
      icon: Icons.memory,
      categoryColor: const Color(0xFFF97316),
    ),
    EnvironmentInfo(
      id: 'sqlite',
      name: 'SQLite',
      description: '轻量级嵌入式 SQL 数据库',
      hint: '轻量级本地数据库，无需安装服务',
      category: EnvironmentCategory.database,
      icon: Icons.storage,
      categoryColor: const Color(0xFFF97316),
    ),

    // ── 云工具 ──────────────────────────────────
    EnvironmentInfo(
      id: 'awscli',
      name: 'AWS CLI',
      description: 'Amazon Web Services 命令行工具',
      hint: '操作亚马逊云服务的命令行工具',
      category: EnvironmentCategory.cloud,
      icon: Icons.cloud_outlined,
      categoryColor: const Color(0xFF64748B),
    ),
    EnvironmentInfo(
      id: 'azcli',
      name: 'Azure CLI',
      description: 'Microsoft Azure 命令行工具',
      hint: '操作微软云服务的命令行工具',
      category: EnvironmentCategory.cloud,
      icon: Icons.cloud_outlined,
      categoryColor: const Color(0xFF64748B),
    ),
    EnvironmentInfo(
      id: 'gcloud',
      name: 'Google Cloud SDK',
      description: 'Google Cloud Platform 命令行工具',
      hint: '操作谷歌云服务的命令行工具',
      category: EnvironmentCategory.cloud,
      icon: Icons.cloud_outlined,
      categoryColor: const Color(0xFF64748B),
    ),
    EnvironmentInfo(
      id: 'terraform',
      name: 'Terraform',
      description: '基础设施即代码 (IaC) 工具',
      hint: '用代码定义和管理服务器基础设施',
      category: EnvironmentCategory.cloud,
      icon: Icons.cloud_sync,
      categoryColor: const Color(0xFF64748B),
    ),
    EnvironmentInfo(
      id: 'heroku',
      name: 'Heroku CLI',
      description: 'Heroku 平台命令行工具',
      hint: '快速部署应用的云平台工具',
      category: EnvironmentCategory.cloud,
      icon: Icons.cloud_upload_outlined,
      categoryColor: const Color(0xFF64748B),
    ),

    // ── 构建工具 ────────────────────────────────
    EnvironmentInfo(
      id: 'make',
      name: 'GNU Make',
      description: '经典构建自动化工具',
      hint: 'Linux/C 项目的经典构建工具',
      category: EnvironmentCategory.buildTool,
      icon: Icons.build_outlined,
      categoryColor: const Color(0xFFEC4899),
    ),
    EnvironmentInfo(
      id: 'cmake',
      name: 'CMake',
      description: '跨平台 C/C++ 项目生成工具',
      hint: 'C/C++ 项目跨平台构建工具',
      category: EnvironmentCategory.buildTool,
      icon: Icons.build_outlined,
      categoryColor: const Color(0xFFEC4899),
    ),
    EnvironmentInfo(
      id: 'ninja',
      name: 'Ninja',
      description: '小而快的构建系统',
      hint: '极速小型构建工具',
      category: EnvironmentCategory.buildTool,
      icon: Icons.flash_on,
      categoryColor: const Color(0xFFEC4899),
    ),
    EnvironmentInfo(
      id: 'ant',
      name: 'Apache Ant',
      description: 'Java 经典构建工具',
      hint: 'Java 项目经典构建工具',
      category: EnvironmentCategory.buildTool,
      icon: Icons.build_outlined,
      categoryColor: const Color(0xFFEC4899),
    ),

    // ── 运行时 & 其他 ───────────────────────────
    EnvironmentInfo(
      id: 'flutter',
      name: 'Flutter',
      description: 'Google 跨平台 UI 框架 (Android/iOS/桌面/Web)',
      hint: '一套代码运行所有平台的 UI 框架',
      category: EnvironmentCategory.runtime,
      icon: Icons.phone_android,
      categoryColor: const Color(0xFF84CC16),
    ),
    EnvironmentInfo(
      id: 'android_adb',
      name: 'Android ADB',
      description: 'Android 调试桥，Android SDK 工具',
      hint: '用于连接和调试 Android 设备',
      category: EnvironmentCategory.runtime,
      icon: Icons.android,
      categoryColor: const Color(0xFF84CC16),
    ),
    EnvironmentInfo(
      id: 'deno',
      name: 'Deno',
      description: 'Node.js 前创始人打造的新 JS 运行时',
      hint: '更安全的下一代 JavaScript 运行时',
      category: EnvironmentCategory.runtime,
      icon: Icons.terminal,
      categoryColor: const Color(0xFF84CC16),
    ),
    EnvironmentInfo(
      id: 'wsl',
      name: 'WSL',
      description: 'Windows Subsystem for Linux（Windows 下运行 Linux）',
      hint: '在 Windows 中运行 Linux 子系统',
      category: EnvironmentCategory.runtime,
      icon: Icons.terminal,
      categoryColor: const Color(0xFF84CC16),
    ),
    EnvironmentInfo(
      id: 'nginx',
      name: 'Nginx',
      description: '高性能 Web 服务器与反向代理',
      hint: '网站服务器和反向代理工具',
      category: EnvironmentCategory.runtime,
      icon: Icons.dns,
      categoryColor: const Color(0xFF84CC16),
    ),
  ];

  /// 按分类获取工具列表
  static Map<EnvironmentCategory, List<EnvironmentInfo>> grouped() {
    final map = <EnvironmentCategory, List<EnvironmentInfo>>{};
    for (final item in all) {
      map.putIfAbsent(item.category, () => []).add(item);
    }
    return map;
  }
}
